<a href="https://colab.research.google.com/github/anjareddy/datascience/blob/main/1_intro_to_linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
x = 25
x

25

**SCALAR VECTORS**

In [2]:
type(x)

int

In [3]:
y =3

In [4]:
py_sum = x + y
py_sum

28

In [5]:
x_float = 25.0
x_float

25.0

In [6]:
import torch

Pytorch tutorials: https://pytorch.org/tutorials/

In [7]:
type(x_float)

float

In [8]:
x_pt = torch.tensor(25, dtype=torch.float32)
x_pt

tensor(25.)

In [9]:
x_pt.size() #[], since scalars have no dimensions

torch.Size([])

Tensor flow: https://www.tensorflow.org/learn

In [10]:
import tensorflow as tf

In [11]:
x_tf = tf.Variable(25, dtype=tf.int16)
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [12]:
x_tf.shape

TensorShape([])

In [13]:
y_tf = tf.Variable(3, dtype=tf.int16)
y_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=3>

In [14]:
x_tf + y_tf

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [15]:
sum_tf = tf.add(x_tf, y_tf)
sum_tf

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [16]:
sum_tf.numpy() # note that NumPy operations automatically convert tensors to NumPy arrays, and vice versa.

28

In [17]:
type(sum_tf.numpy())

numpy.int16

In [18]:
tf_float = tf.Variable(25, dtype=tf.float16)
tf_float

<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=25.0>

**ARRAYS** (2-D Vectors)

In [19]:
import numpy as np

In [23]:
x = np.array([1, 2, 3, 5, 9])
x
f = np.array([1, 2, 3, 5.], dtype=np.float16)
f

array([1., 2., 3., 5.], dtype=float16)

In [24]:
len(x)

5

In [26]:
type(x)

numpy.ndarray

In [27]:
x[0]

1

In [28]:
x.T

array([1, 2, 3, 5, 9])

In [29]:
y = np.array([[1, 2, 3, 5, 9]])

In [30]:
y.T

array([[1],
       [2],
       [3],
       [5],
       [9]])

In [33]:
y.shape

(1, 5)

In [34]:
y.T.shape

(5, 1)

In [36]:
z = np.zeros(9)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
pt_array = torch.tensor([1, 2, 3, 4, 5, 6, 7])
pt_array

tensor([1, 2, 3, 4, 5, 6, 7])

In [39]:
tf_array = tf.Variable([1, 2, 3, 4, 5, 6, 7, 8])
tf_array

<tf.Variable 'Variable:0' shape=(8,) dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [40]:
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

**NORMS**


In [41]:
x

array([1, 2, 3, 5, 9])

In [45]:
(1**2 + 2**2 + 3**2 + 5**2 + 9**2) **(1/2) # L2 norm

10.954451150103322

In [46]:
np.linalg.norm(x)

10.954451150103322

In [47]:
np.abs(x[0]) + np.abs(x[1]) + np.abs(x[2]) + np.abs(x[3]) + np.abs(x[4])

20

In [48]:
(1**2 + 2**2 + 3**2 + 5**2 + 9**2) # squared L2 Norm

120

In [49]:
np.dot(x, x)

120

**Orthognal Vectors XT multiply Y = 0**

In [51]:
i = np.array([1, 0]) #x
i

array([1, 0])

In [52]:
j = np.array([0, 1]) #y
j

array([0, 1])

In [53]:
np.dot(i, j)

0

2-D VECTORS (MATRICES)

In [58]:
X = np.array([[11, 12, 13], [21, 22, 23]])
X

array([[11, 12, 13],
       [21, 22, 23]])

In [61]:
X.shape # 2rows, 3 columns

(2, 3)

In [60]:
X.size

6

In [62]:
X[:1]

array([[11, 12, 13]])

In [65]:
X[:,0]

array([11, 21])

In [67]:
X[0, :] # VECTOR TENSOR

array([11, 12, 13])

In [68]:
X[1, :]

array([21, 22, 23])

In [69]:
X[0:2, 0:2]

array([[11, 12],
       [21, 22]])

In [71]:
X_pt = torch.tensor([[11, 12, 13], [21, 22, 23]])
X_pt

tensor([[11, 12, 13],
        [21, 22, 23]])

In [72]:
X_pt.shape

torch.Size([2, 3])

In [74]:
X_pt.size()

torch.Size([2, 3])

In [75]:
X_tf = tf.Variable([[11, 12, 13], [21, 22, 23]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[11, 12, 13],
       [21, 22, 23]], dtype=int32)>

In [80]:
#X_tf.shape
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [81]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [82]:
tf.size(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

**High Dimensional Vectors**

In [83]:
 images_pt = torch.zeros([32, 28, 28, 3])
 images_pt

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         ...,

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0.

In [84]:
images_tf = tf.zeros([32, 28, 28, 3])
images_tf

<tf.Tensor: shape=(32, 28, 28, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


   

**Tensor Transposition**

In [85]:
X

array([[11, 12, 13],
       [21, 22, 23]])

In [86]:
X.T

array([[11, 21],
       [12, 22],
       [13, 23]])

In [90]:
tf.transpose(X_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 21],
       [12, 22],
       [13, 23]], dtype=int32)>

In [91]:
X_pt.T

tensor([[11, 21],
        [12, 22],
        [13, 23]])

In [92]:
X_pt.H

tensor([[11, 21],
        [12, 22],
        [13, 23]])

In [93]:
Y = X + 2
Y

array([[13, 14, 15],
       [23, 24, 25]])

In [95]:
Z = X*2
Z

array([[22, 24, 26],
       [42, 44, 46]])

In [96]:
X + Y

array([[24, 26, 28],
       [44, 46, 48]])

In [98]:
 X * Y

array([[143, 168, 195],
       [483, 528, 575]])

above operations are same in PyTorch and Tensor flow

In [100]:
X.sum() #numpy

102

In [101]:
X_pt.sum() #pytorch

tensor(102)

In [102]:
torch.sum(X_pt)

tensor(102)

In [103]:
tf.reduce_sum(X_tf) #tensorflow

<tf.Tensor: shape=(), dtype=int32, numpy=102>

In [104]:
X.sum(axis = 0)


array([32, 34, 36])

In [105]:
X

array([[11, 12, 13],
       [21, 22, 23]])

In [106]:
torch.sum(X_pt, 0)

tensor([32, 34, 36])

In [107]:
tf.reduce_sum(X_tf, 0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([32, 34, 36], dtype=int32)>

In [113]:
XT_tf = tf.transpose(X_tf)
XT_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 21],
       [12, 22],
       [13, 23]], dtype=int32)>

In [119]:
x_1 = np.array([1, 2, 3, 4, 5])
x_1

array([1, 2, 3, 4, 5])

In [121]:
x

array([1, 2, 3, 5, 9])

In [122]:
np.dot(x, x_1)

79

NameError: ignored