<a href="https://colab.research.google.com/github/anjareddy/datascience/blob/main/1_intro_to_linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
x = 25
x

25

In [2]:
type(x)

int

In [3]:
y =3

In [4]:
py_sum = x + y
py_sum

28

In [5]:
x_float = 25.0
x_float

25.0

In [6]:
import torch

Pytorch tutorials: https://pytorch.org/tutorials/

In [7]:
type(x_float)

float

In [8]:
x_pt = torch.tensor(25, dtype=torch.float32)
x_pt

tensor(25.)

In [9]:
x_pt.size() #[], since scalars have no dimensions

torch.Size([])

Tensor flow: https://www.tensorflow.org/learn

In [10]:
import tensorflow as tf

In [11]:
x_tf = tf.Variable(25, dtype=tf.int16)
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [12]:
x_tf.shape

TensorShape([])

In [13]:
y_tf = tf.Variable(3, dtype=tf.int16)
y_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=3>

In [14]:
x_tf + y_tf

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [15]:
sum_tf = tf.add(x_tf, y_tf)
sum_tf

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [16]:
sum_tf.numpy() # note that NumPy operations automatically convert tensors to NumPy arrays, and vice versa.

28

In [17]:
type(sum_tf.numpy())

numpy.int16

In [18]:
tf_float = tf.Variable(25, dtype=tf.float16)
tf_float

<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=25.0>

In [19]:
import numpy as np

In [23]:
x = np.array([1, 2, 3, 5, 9])
x
f = np.array([1, 2, 3, 5.], dtype=np.float16)
f

array([1., 2., 3., 5.], dtype=float16)

In [24]:
len(x)

5

In [26]:
type(x)

numpy.ndarray

In [27]:
x[0]

1

In [28]:
x.T

array([1, 2, 3, 5, 9])

In [29]:
y = np.array([[1, 2, 3, 5, 9]])

In [30]:
y.T

array([[1],
       [2],
       [3],
       [5],
       [9]])

In [33]:
y.shape

(1, 5)

In [34]:
y.T.shape

(5, 1)

In [36]:
z = np.zeros(9)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
pt_array = torch.tensor([1, 2, 3, 4, 5, 6, 7])
pt_array

tensor([1, 2, 3, 4, 5, 6, 7])

In [39]:
tf_array = tf.Variable([1, 2, 3, 4, 5, 6, 7, 8])
tf_array

<tf.Variable 'Variable:0' shape=(8,) dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [40]:
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>